### ISSUE TITLE
Please release VOOC/DASH fast charge source code!

### ISSUE THREAD

**Issue by moetayuko** [OnePlusOSS/android_kernel_oneplus_msm8996#1]
@JayFan1201

**Comment by leonfish77101** [comment]
We are working on it, please be patient..

**Comment by simonsmh** [comment]
@leonfish77101 When will your guys release the source code or the binary? Please give out a clear time.

**Comment by leonfish77101** [comment]
@simonsmh we will release DASH at the end of July by binary

**Comment by julian-klode** [comment]
@leonfish77101 Well, the code running in the kernel has to be GPL licensed (or less restrictive), and you have to provide it, there's no way around that. That's a GPL requirement.

And if someone receives the phone and asks for the source code, you have to provide the source code used to build the binary shipped on the phone. And all code that is part of the binary is subject to the GPL.

**Comment by leonfish77101** [comment]
@julian-klode You are right, we will release all DASH codes which under GPL license. 

In fact, we will release DASH as two parts: one part is kernel source code, such as GPIO; and the other is Oneplus proprietary. For the business consideration, Oneplus proprietary will be released as binary.

**Comment by moetayuko** [comment]
It's okay, we just want to get it functional, I don't care if I can access to source code

**Comment by julian-klode** [comment]
@leonfish77101 That does sound better. I'm not sure what business considerations there are, given that OPPO already published their entire working VOOC source code (well, the firmware running on the PIC microcontrollers are blobs, but I think you want to have more blobs...), but then I have not seen the end product and do not know the difference to VOOC (if there is any, if not, it's kind of pointless).

**Comment by leonfish77101** [comment]
@julian-klode can you give me a link to OPPO's VOOC source code?

**Comment by julian-klode** [comment]
@leonfish77101 There's a ton of code in https://github.com/oppo-source/R7plus-5.1-kernel-source/tree/master/drivers/power/oppo, among them oppo_vooc.c and oppo_vooc.h.

**Comment by moetayuko** [comment]
@leonfish77101 searching "fastcg" in every oppo kernel repository you'll find.
Even in oneplus x kernel: https://github.com/OnePlusOSS/android_kernel_oneplus_msm8974/search?utf8=%E2%9C%93&q=fastcg&type=Code

**Comment by julian-klode** [comment]
BTW, the R7Plus kernel was a bit reorganized compared to previous OPPO kernel releases - the OPPO stuff is now in an oppo/ subdirectory of drivers/power. And pic16F1503_fastcg.c was basically renamed to oppo_vooc.c and extended a bit.

**Comment by Sumitmitra25** [comment]
Will rooting break my dash carge in my op3

**Comment by gssdromen** [comment]
@Sumitmitra25 Dash charge works well after rooting for me

**Comment by simonsmh** [comment]
@Sumitmitra25 Dash works always well on the stock kernel.

**Comment by FurFlowery** [comment]
we need DASH fast charge source code.We need it.Pleace give us. @leonfish77101

**Comment by simonsmh** [comment]
@yunalan Wait it until the end of July.

**Comment by toffyjan** [comment]
Should I use msm_defconfig for compiling kernel or msm-perf_defconfig? I tried both but end up with wifi is not working. I also copied modules from lib and flashed.. but there is still problem with wifi. 

Any idea's / suggestions ..Thanks

**Comment by leonfish77101** [comment]
I think msm-perf_defconfig is good. 
Check this code in AndroidBoard.mk:

ifeq ($(KERNEL_DEFCONFIG),)
    ifeq ($(TARGET_BUILD_VARIANT),user)
      KERNEL_DEFCONFIG := msm-perf_defconfig
    else
      KERNEL_DEFCONFIG := msm_defconfig
    endif
endif

May be you missed wifi module which have to pulled from the device. You can check the script I uploaded in "android" repository named pull_library.sh for more details about wifi driver

**Comment by toffyjan** [comment]
But I'm compiling only kernel from the sources. Every thing is working fine. Have only wifi problem. Maybe I should pull from my device.. Thanks

**Comment by youngchaos** [comment]
@toffyjan  refer to this maybe could help -> http://forum.xda-developers.com/showpost.php?p=67476935&postcount=47

**Comment by shifty0g** [comment]
Is this still comming end of july?

**Comment by DragosStefan** [comment]
Any new informations about the release date?

**Comment by mattdholloway** [comment]
Still the end of July?

**Comment by pahofmann** [comment]
Any news on the release date?

**Comment by jcespi2005** [comment]
Winter is comming ;) Any news?

**Comment by lucasreiners** [comment]
5 days left :stuck_out_tongue:

**Comment by flar2** [comment]
Would be really nice to get updated kernel source as well.  It's been a few weeks since the latest OTA rolled out.

**Comment by flar2** [comment]
And now I see a 3.2.2 OS update rolling out.  

Please update the kernel source as per GPL requirements.

**Comment by p40** [comment]
Are you going to release it on time?

**Comment by KamikazePlatypus** [comment]
inb4 delayed indefinitely

**Comment by maurisy0** [comment]
Really? Delayed? Smh its the 27th already 🙁
And how about the camera? Will it be possible to have it in custom roms? Camera quality is poor with custom roms.

**Comment by simonsmh** [comment]
I'm not the developer and I know nothing about this situation. I tried the
ported oos stock camera in XDA, which perform well enough in cm for daily
use.

maurisy0 notifications@github.com于2016年7月27日周三 上午8:28写道：

**Comment by maurisy0** [comment]
@simonsmh
Hey bud, thanks but I knew it that already. 
It'll be easier if they could make the apk available in the playstore tho. So no more porting needed. Guys trying to port it is having a quite a hard time figuring it out.

**Comment by hsareminia** [comment]
please ........
what happened?
please  realese source code DASH.........

**Comment by maurisy0** [comment]
and please update the kernel source. make if complete and up to date please.
what's the point if it's half baked then nothing more.

**Comment by hsareminia** [comment]
hi
i dont know why not realese?
i am worry .

**Comment by shifty0g** [comment]
would be nice to have an update

**Comment by julian-klode** [comment]
From the commit message, that seems to be fixed in commit 38dd8d898321801498f85d84f434fa7a9de2b992 
But I have not tested it, so not sure if it's complete, or if something is missing.

**Comment by leonfish77101** [comment]
Guys, Dash is uploaded, please re-sync all repositories I mentioned below, and build.
android_vendor_qcom_thulium
android_vendor_oneplus_oneplus3
android_kernel_oneplus_msm8996
android_device_qcom_sepolicy

**Comment by libcg** [comment]
Can someone close this issue now?

**Comment by warmchang** [comment]
mark
