### ISSUE TITLE
JUNK FS

### ISSUE THREAD

**Issue by scafroglia93** [OnePlusOSS/android_kernel_oneplus_msm8996#17]
Please remove this deprecated FS from defconfig please
![schermata del 2016-11-22 01-02-17](https://cloud.githubusercontent.com/assets/8227101/20505938/acb1ea0a-b050-11e6-9590-513bc72ebeb4.png)

**Comment by brucechiu1113** [comment]
Since we already migrated to Android N, it will be removed on Android N's next OTA. Thanks for your suggestion.

**Comment by NewEraCracker** [comment]
This issue still persists on OnePlus source code. However, it's relatively easy to fix and does not cause any backward compatibility issue that I'm aware of.
