### ISSUE TITLE
Update 3T kernel source to 3.5.3

### ISSUE THREAD

**Issue by dustin84** [OnePlusOSS/android_kernel_oneplus_msm8996#19]
I figure there are changes to fix touch latency,etc per the changelog. Also, gestures are definitely broken.

**Comment by v7xda** [comment]
@leonfish77101 Please update the kernel sources for 3 and 3T.OTAs were released 3-4 days ago.

**Comment by NewEraCracker** [comment]
There's some activity today.
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commits/oneplus3T/6.0.1

**Comment by dustin84** [comment]
New sources still don't fix off screen gestures

**Comment by leonfish77101** [comment]
@dustin84 From kernel event, we found kernel responses the gesture  event:
<3>[20161129_14:08:09.861494]@3 synaptics,s3320: detect (>) gesture
<3>[20161129_14:08:10.688074]@2 synaptics,s3320: detect (double tap) gesture
<3>[20161129_14:08:12.689500]@0 synaptics,s3320: detect (<) gesture
<3>[20161129_14:08:14.932218]@0 synaptics,s3320: detect (^) gesture

**Comment by dustin84** [comment]
Going to try from a clean base. After I fix all the compilation errors.

**Comment by leonfish77101** [comment]
Turn on off gesture first: echo "~" > proc/touchpanel/gesture_enable

**Comment by dustin84** [comment]
still not working even after turning gestures on off
