### ISSUE TITLE
Please fix the camera name in DTS

### ISSUE THREAD

**Issue by alexlabs** [OnePlusOSS/android_kernel_oneplus_msm8996#22]
In file  arch/arm64/boot/dts/15801_PVT/msm8996-camera-sensor-mtp.dtsi, I found the sub camera is imx179. It  is not the correct information for OnePlus3T . Please update it

**Comment by brucechiu1113** [comment]
Hi Alex,

The file arch/arm64/boot/dts/15801_PVT/msm8996-camera-sensor-mtp.dtsi is for OnePlus3, not for OnePlus 3T. You could refer to arch/arm64/boot/dts/15811_PVT3/msm8996-camera-sensor-mtp.dtsi for correct information you wanted.

Thanks,
Bruce

**Comment by alexlabs** [comment]
Hi Bruce,

        Thanks a lot!  I forgot to switch the branch for OnePlus3T.
It should be  on https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/tree/oneplus3T/6.0.1
