### ISSUE TITLE
crpl.ko source code is missing from OP3T tree

### ISSUE THREAD

**Issue by engstk** [OnePlusOSS/android_kernel_oneplus_msm8996#24]
Provide the crpl.ko source code.
There's no reason for the sources that are being pushed continue to be half broken and with stuff missing and/or omitted.

Source must match the compiled binaries shipped with the device.
Respect GPL.

**Comment by xboxfanj** [comment]
Core CTL is not open source (for most of the shipped devices), nor is the exact qca WLAN driver. Technically, external kernel modules do not necessarily fall under GPL.

**Comment by engstk** [comment]
Yet distribution of proprietary modules is tolerable, makes no sense for a "developer friendly" company and renders the devicemunusable in it's full potential.
They have a qca repo at least, so no issues there.

OP has an history of pushing broken source that clearly doesn't match the shipped binaries, just take a look to the latest derped touchscreen drivers that have gestures broken since they shipped OP3T source.

Makes no sense.

**Comment by brucechiu1113** [comment]
Hi @engstk 

The source code of crpl.ko were committed, you could have a try.
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commit/f996d96250b345a6c66daf469df41ab8cce25d43

Thanks,
Bruce

**Comment by DevriesL** [comment]
@brucechiu1113 
I do not why OnePlus rack their brains to avoid open this part of source code, there is no company has interest in copying your *coretech*...

**Comment by NewEraCracker** [comment]
I've dumped the strings of the module. It is BSD licensed and uses APIs embedded in the Kernel. The source code of the APIs themselves has been disclosed and the module is now partially shared.

From a licensing compliance standpoint on this matter, like it or not, OnePlus is in full compliance.

http://pastebin.com/RsW15Vnq

**Comment by engstk** [comment]
Thanks @brucechiu1113 should be good to go now.

**Comment by julian-klode** [comment]
@NewEraCracker No, that argument is wrong. It is in fact explicitly in violation since it explicitly uses functions which were explicitly marked as GPL-only (their authors declaring that use of the symbol definitely creates a derivative work in their point of view, instead of just likely a derivate work).

They added wrappers around these EXPORT_SYMBOL_GPL functions - new functions that just call the other functions. This is silly - it does not free you from any obligations of the GPL.

**Comment by julian-klode** [comment]
And note that it does not matter at all whether the code is BSD licensed. The BSD license is compatible with the GPL, and by combining the kernel with the BSD licensed code, the BSD licensed code becomes subjects to the terms of the GPL as well.

**Comment by NewEraCracker** [comment]
@julian-klode Interesting. Thanks for correcting.
