### ISSUE TITLE
Nougat kernel source for OP3/3T

### ISSUE THREAD

**Issue by moetayuko** [OnePlusOSS/android_kernel_oneplus_msm8996#26]

**Comment by singingtelegram** [comment]
+1. @leonfish77101

**Comment by Martinusbe** [comment]
#patientlywaitng ...

**Comment by NewEraCracker** [comment]
... And the million dollar question is if it will have the latest security fixes for CAF advisories.

**Comment by engstk** [comment]
2 OTAs and no source to be seen.
@brucechiu1113 it's about time, help us out here.

**Comment by aaronqiuchiu** [comment]
@engstk you can got android 7.0 soruce code from:
git  repertory:  https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996.git
branch:  oneplus/QC8996_N
