### ISSUE TITLE
[GPL] Source code not up to date

### ISSUE THREAD

**Issue by flar2** [OnePlusOSS/android_kernel_oneplus_msm8996#3]
Please release updated kernel source.  There have now been three OTA updates for this device since the kernel source was last updated.

**Comment by engstk** [comment]
I'm with you flar.

Damn shameful that we kernel developers are more GPL compliant than the company that push out the original sources.

Every Oxygen OS update must have the COMPLETE source (not the half done stuff with missing features) posted after the OTA release.

So much for the "Developer friendly" showoff...

**Comment by franciscofranco** [comment]
It's no use. Their chinese politics just get in the way. I've been pressing them as much as possible, even offered to help. We're just fucked until then.

**Comment by Pafcholini** [comment]
I'm very disappointed...I hope they will upload it soon.

**Comment by maurisy0** [comment]
and you advertised the phone to be developer friendly. very disappointing tbh.
please please please update it. and include the other stuff missing. please

**Comment by Raulvo** [comment]
As long as they end up updating the repository, all is OK. But... what if not? A delay of two weeks since the latest OTA is alright.

**Comment by flar2** [comment]
@Raulvo 
No, it's not alright.  They are violating the GPL and making things difficult for developers and users.

If they use a version control system like git, they can upload their source code changes in literally seconds.  Even if they want to be purposely opaque and combine all their changes into one commit (e.g. "add OnePlus modification"), it would still only take a few minutes of effort.

**Comment by velamir** [comment]
@flar2 

something like this? https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commit/38dd8d898321801498f85d84f434fa7a9de2b992

**Comment by Raulvo** [comment]
@flar2 The GPL does not say anything about timing. And does not say nothing about how you can get the source. In fact, they could close this repository and still not violate the GPL. Because the source code must be available for anyone who wants it, for anyone who asks for it.

But I agree that the repository should have been already updated. Maybe they have multiple branches with the changes scattered all over them and use a script to download the source parts from the different repositories and compile. Who knows.

**Comment by julian-klode** [comment]
@Raulvo OnePlus violates the GPL in any case. Let's take a look at the options for satisfying section 3:

a) Accompany binary with source - Not satisfied
b) Include written offer, valid for 3 years - Not satisfied
c) Include information you received (for non-commercial use) - Not satisfied

Now, most phone manufacturers include a paragraph in the user guide / warranty info to exercise option b) as that is certainly the only way to follow the GPL for a phone, unless you want to ship the source code for the initial phone image in the phone packaging.

Well, if you interpret liberally, you can also accompany the binary by "offering access to copy from a designated place", as the end of section 3 says. But well, that's kind of grey zone.

**Comment by Raulvo** [comment]
@julian-klode 
I assumed OnePlus provided the GPL notice with the phone, and a link to download the source from or e-mail to contact with. I do not have the phone hehe.

**Comment by Pafcholini** [comment]
Finally OP uploaded the commit!

**Comment by BoredOutOfMyGit** [comment]
#AlwaysSettle

**Comment by Fahadali2315** [comment]
This is bad even if its related to the chinese politics , they should not be selling off the device as international in the first place then. Three devices and they are still lacking .

**Comment by scafroglia93** [comment]
History repeats itself

**Comment by parasaviator** [comment]
Hope this serious issue gets noticed.... we have the best devs complaining...update it before they leave this device like they abandoned op2
@leonfish77101 expecting a firm reply

**Comment by scafroglia93** [comment]
This is OnePlus!

https://www.change.org/p/oneplus-release-sources-for-oxygen-os-we-need-more-development

Last year they released nothing and strangely now releasing everything and nothing

https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by flar2** [comment]
@leonfish77101  Are there any kernel changes in the 3.2.4 update?

**Comment by scafroglia93** [comment]
OnePlus has entered a new commit LOL

**Comment by ghost** [comment]
@leonfish77101 When can we expect kernel source update including pocket mode?

**Comment by scafroglia93** [comment]
@leonfish77101 Please, respect GPL

**Comment by NewEraCracker** [comment]
Problem is OnePlus is based in China. Even if someone wanted to pursue claims over intelectual property (GPL licensed code) infringement due to (partial) source non-disclosure, a Chinese court would just dismiss it. Taking the example of Hellwig vs VMware (GPL licensing claim) so far court dismissed lawsuit.

**Comment by Habylab** [comment]
@leonfish77101 can you please update the source for the 7.0 update? It's shameful that you aren't complying with GPL.

There's plenty of good, and hugely influential developers, in this one thread criticising you. And you just sit there and do nothing?

**Comment by nezorflame** [comment]
Guys, seems that source has been pushed!
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commit/73954d7ffb1c97acabc85c99cba4346dee2e7f6d

**Comment by scafroglia93** [comment]
With super squashed commit lol

**Comment by aaronqiuchiu** [comment]
Guys, OnePlus 3/3T Android 7.0 source code has been pushed
git repertory: https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996.git
branch: oneplus/QC8996_N
