### ISSUE TITLE
Please disclose the exact configuration and commands used to build the kernel

### ISSUE THREAD

**Issue by NewEraCracker** [OnePlusOSS/android_kernel_oneplus_msm8996#30]
Hello,

I hereby request that OnePlus team discloses the configuration they've used to build the kernel tree.

I have managed to build it and applied it over the boot image of the device, yet all get is the screen turning off and a white-led during boot, signaling a catastrophic failure.

This is the config I am using:
https://github.com/VPSrv/android_kernel_oneplus_msm8996/blob/newera/QC8996_N/arch/arm64/configs/newera_oneplus3_defconfig
Anything I am missing and need to be enabled?

Regards,
Jorge M. Oliveira aka NewEraCracker

**Comment by jcadduono** [comment]
I built this with msm-perf_defconfig (which does have oneplus's modifications)

https://build.nethunter.com/test-builds/oneplus/oneplus_stock_test-1-20170120-1625.zip

please let me know if it boots, it has a drastically different size for dtb and kernel image than the actual 4.0.2 release boot.img

note: you should make a system image (it replaces stock kernel modules unless you remove modules folder from zip) and boot partition backup before flashing

you will need to flash it over the stock boot image from TWRP.

sources: https://github.com/jcadduono/android_kernel_oneplus_msm8996/commits/android-7.0
(includes build script, etc)

installer zip: https://github.com/jcadduono/lazyflasher
place `build/arch/arm64/boot/Image.gz-dtb` and `build/lib/modules` in there `make NAME=oneplus_stock_test VERSION=1`

keep in mind that changing any configs can cause null pointer dererferences and kernel panics and will need thorough debugging to solve (pstore pull from twrp, etc)
no manufacturer tests anything other than what they ship with, go figure

still waiting for oneplus to consider donating a 3T so i can work on getting this all solved for the community

sincerely, 
the guy who made the official twrp builds that appears to have problems for 5% of users

**Comment by NewEraCracker** [comment]
@jcadduono Thanks a lot! Your image does boot. I'll have to check what's wrong at my side on the custom build.

**Comment by jcadduono** [comment]
feel free to rebase on top of my sources if it helps!

**Comment by NewEraCracker** [comment]
@jcadduono Just leaving a final note here. I was able to build my own custom kernel for OOS N with your configuration and respective tools.
