### ISSUE TITLE
Please fix broken off screen gestures Not Working in One Plus 3 [ Nougat ]

### ISSUE THREAD

**Issue by maddalakum** [OnePlusOSS/android_kernel_oneplus_msm8996#31]
Screen off gestures Not Working Please Help me to Fix . Thanks in Advance

**Comment by aaronqiuchiu** [comment]
@maddalakum please  reference the following answer and try it .
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/issues/21

Thanks
