### ISSUE TITLE
OOS 4.1.3 source

### ISSUE THREAD

**Issue by dustin84** [OnePlusOSS/android_kernel_oneplus_msm8996#34]
Will there be any new commits with the latest update?

**Comment by NewEraCracker** [comment]
It's time to update title to "OxygenOS 4.1.3 Source".

**Comment by dustin84** [comment]
Done.

Edit: Now it's done.

**Comment by dustin84** [comment]
@aaronqiuchiu @leonfish77101  Can you help us out here?

**Comment by aaronqiuchiu** [comment]
@dustin84 thanks for your remind, and for OOS 4.1.3 there is no any modification with OOS 4.1.0 in kernel source. so there is no any commints for OOS 4.1.3. 

Thanks

**Comment by dustin84** [comment]
@aaronqiuchiu Ok, thanks for the response.  I'll close this issue then.
