### ISSUE TITLE
dash充电电流是否正确？

### ISSUE THREAD

**Issue by zhuqiang0320** [OnePlusOSS/android_kernel_oneplus_msm8996#35]
我看到贵司释放的代码中，qcom,fastchg-current-ma = <2000>，但是dush标配充电器不是5V/4A的吗，为什么快充电流才是2A？

**Comment by aaronqiuchiu** [comment]
dash 快充电流是由mcu控制的，非AP跟PMIC控制，所以dtsi里面的配置不起作用！
