### ISSUE TITLE
Which Is The Proper Branch?

### ISSUE THREAD

**Issue by robbins** [OnePlusOSS/android_kernel_oneplus_msm8996#41]
The 8.0.0 Beta or just 8.0.0?

**Comment by ItzLevvie** [comment]
```QC8996_O_8.0.0_Beta``` is the branch for Open Beta channel
```QC8996_O_8.0.0``` is the branch for Stable channel

**Comment by robbins** [comment]
How do I build for the Open Beta channel? https://github.com/OnePlusOSS/android/tree/oneplus/QC8996_O_8.0 doesn't have a beta branch.

**Comment by robbins** [comment]
Ah ok, I see your edit. Thanks! 👍 
 
Probably should open a separate issue for this, but I'm getting this error when building on the non beta branch: https://hastebin.com/neworemiji.sql 

Is it possible you can shed any light on this error? I'll open another issue and post a full log so that other people can take a look at it as well if necessary.

**Comment by dustin84** [comment]
It doesn't appear to be kernel related from the your logs.

**Comment by ItzLevvie** [comment]
_**'How do I build for the Open Beta channel?'**_

The kernel used in the Open Beta channel is published in ```QC8996_O_8.0.0_Beta``` if you want to build it with https://github.com/OnePlusOSS/android/tree/oneplus/QC8996_O_8.0, I'm guessing you can change it in the manifest file

**Comment by NateDev100** [comment]
@ItzLevvie Ok, thanks :)

@dustin84 If it's not kernel related where should I be directing this issue to then? The "android" repo basically as a general issue, or what? I just assumed it was a kernel issue as it was doing stuff in the kernel directory and Image.gz-dtb which is kernel stuff, etc. but you probably know better than me haha!

**Comment by GeekZJJ** [comment]
@ItzLevvie  I use the kernel source "https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/tree/oneplus/QC8996_O_8.0.0_Beta" and the toolchain "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9".
Then I compile by using the following steps.
1.set environment variables in .bashrc:
PATH=$PATH:<the path to the toolchain's bin folder>
export CROSS_COMPILE=aarch64-linux-android-
export ARCH=arm64
export SRCARCH=arm64
export SUBARCH=arm64
2.in the kernel source directory :
make msm_defconfig(also try msm-perf_defconfig)
make -j4
3.backup the boot.img in my phone and extract the kernel in it. Then replace the kernel with the one I compiled in the arch/arm64/boot/Image.gz-dtb. Then repack the new boot.img
4.flash the new boot.img.
But after i reboot my phone it stuck at the oneplus logo with "power by android".
Is there anything wrong with my steps? I have try several possibility solutions but no one worked. Thanks very much.
