### ISSUE TITLE
5.0.8?

### ISSUE THREAD

**Issue by AKoskovich** [OnePlusOSS/android_kernel_oneplus_msm8996#43]
The kernel sources are 4 versions out of date now. Doesn't this violate the GPL? It's been nearly a year since the last update was pushed.

**Comment by MegaLiu** [comment]
Devicetree for OnePlus 3/3T OxygenOS 5.0.8 has been released
https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commits/oneplus/QC8996_O_8.0.0

**Comment by AKoskovich** [comment]
Thanks. :)

**Comment by brucechiu1113** [comment]
David, thanks for your great efforts.
