### ISSUE TITLE
Will there be sources pushed for OOS 9.0.2?

### ISSUE THREAD

**Issue by AKoskovich** [OnePlusOSS/android_kernel_oneplus_msm8996#44]
Since the beta came out today, thought I'd ask if sources would be updated.

**Comment by AKoskovich** [comment]
Stable release came out today. Will sources be released for it?

**Comment by Idontunderstandhowkernelworks** [comment]
Waiting for the sources. What's the delay?

**Comment by abimagnus** [comment]
Waiting patiently !

**Comment by AKoskovich** [comment]
Sources were pushed. Thank you.
