### ISSUE TITLE
Please update the kernel source

### ISSUE THREAD

**Issue by moetayuko** [OnePlusOSS/android_kernel_oneplus_msm8996#8]
@leonfish77101 the current OSS kernel doesn't boot with latest bootloader, please update the source.

**Comment by leonfish77101** [comment]
@dianlujitao Which build you use?

**Comment by moetayuko** [comment]
Both bootloader from latest Hydrogen and Oxygen

**Comment by moetayuko** [comment]
Both bootloader from latest Hydrogen and Oxygen

**Comment by leonfish77101** [comment]
please show me the build number

**Comment by moetayuko** [comment]
OnePlus3Hydrogen_16_OTA_002_all_1609130645_7dd2f72a286144b5.zip from http://www.h2os.com/download (公测版)
OnePlus3Oxygen_16_OTA_003_all_1609142002_2a17363c90cd462e.zip from http://downloads.oneplus.net/oneplus-3/oneplus_3_oxygenos_3.5.2_community_build/

**Comment by leonfish77101** [comment]
oh yes~these are the latest build, we will release source code in the several days when we release this build globally

**Comment by v7xda** [comment]
@leonfish77101 How about the 3.2.6 sources?OTA is available since last day.

**Comment by leonfish77101** [comment]
@v7xda I have answered already

**Comment by engstk** [comment]
@leonfish77101 Those builds are betas, but 3.2.6 is already being distributed worldwide so source must follow ASAP.
But even in the case of distributing betas (so called community builds), there's no reason to not comply with GPL: Google pushes kernel sources for preview builds, so should you

**Comment by moetayuko** [comment]
@leonfish77101 still not boot with https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/commit/5ac8dc344aa5242cadae5f8010497e6b2869575c

It failed at https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/blob/oneplus3/6.0.1/drivers/soc/qcom/project_info.c#L367 , please double check if struct project_info matches sbl1

**Comment by moetayuko** [comment]
@leonfish77101 btw please update dts as well, I reversed the stock dtbs and found it different from the OSS one, please respect GPL

**Comment by NewEraCracker** [comment]
Any news? 3.2.7 and 3.2.8 have been released. Didn't you guys changed a bit in the kernel to fix the recent security vulnerabilities such as dirty cow?

@OnePlusOSS @OnePlusOSSAdmin @leonfish77101 @JayFan1201

**Comment by aaronqiuchiu** [comment]
OnePlus 3/3T Android 7.0 soruce code has released
git repertory: https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996.git
branch: oneplus/QC8996_N
